services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: nobinuser
      WORDPRESS_DB_PASSWORD: nobinpass
      WORDPRESS_DB_NAME: nobindb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nobindb
      MYSQL_USER: nobinuser
      MYSQL_PASSWORD: nobinpass
      MYSQL_ROOT_PASSWORD: 12
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
